### ISSUE TITLE
2.1.1 breaks visible scaling

### ISSUE THREAD

**Issue by re11ding** [PikachuPenial/Infoholic#4]
If using 2.1.1, when scaling text, it does not shift on the fly. You must hide and reshow the stats to make the change apparent. This issue does not exist in 2.1.0. This occurs even with all other mods disabled.

**Comment by PenialJackson** [comment]
Will look into it later this week, thank you for letting me know!

**Comment by PenialJackson** [comment]
> If using 2.1.1, when scaling text, it does not shift on the fly. You must hide and reshow the stats to make the change apparent. This issue does not exist in 2.1.0. This occurs even with all other mods disabled.

Fixed the issue and will be pushing an update to Thunderstore shortly, thank you again for reporting the issue <3
